# Generated by Django 5.0.6 on 2026-06-13 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
