# Generated by Django 5.0.6 on 2026-06-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_expense_created_at_expense_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='monthly_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly budget limit', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
