# Generated by Django 5.0.6 on 2026-06-13 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_alter_category_monthly_limit_alter_expense_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
    ]
