# Generated by Django 5.0.6 on 2026-06-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_alter_category_options_alter_category_monthly_limit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterField(
            model_name='category',
            name='monthly_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly budget limit in USD', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('NPR', 'NPR'), ('INR', 'INR'), ('AUD', 'AUD')], default='USD', max_length=3),
        ),
    ]
