# Generated by Django 5.0.6 on 2026-06-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_alter_category_options_alter_category_monthly_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
